version: 2
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - release
jobs:
  test:
    docker:
      - image: circleci/node:8.9-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Rebuild node sass
          command: npm rebuild node-sass

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Run tests
          command: NODE_ENV=CI npm run test

      # run code coverage
      - run:
          name: Code coverage report
          command: NODE_ENV=CI npm run coverage

      - run:
          name: Upload code coverage report
          command: ./node_modules/codecov/bin/codecov
  release:
    docker:
      - image: 'circleci/node:8.9'
    steps:
      - checkout

      - run:
          name: Rebuild node sass
          command: npm rebuild node-sass

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build UI
          command: npm run build-ui:prod

      - run:
          name: Build Reporter
          command: npm run build-reporter

      - run:
          name: Publish Package
          command: npm run semantic-release || true
          require:
            - test
