version: 2
jobs:
  test:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Run tests
          command: npm run test

      # run code coverage
      - run:
          name: Code coverage report
          command: npm run coverage

      - run:
          name: Upload code coverage report
          command: ./node_modules/codecov/bin/codecov
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
